### PR TITLE
Add /rules and update repo

### PR DESCRIPTION
**Pull request by AtditC**

### CODE REVIEW

**Comment by danielgulic** [comment]
This is assuming the server running the plugin is Warzone, which we do not do. Make the rules link an option in the config, then amend your PR.

**Comment by TRose2000** [comment]
> This is assuming the server running the plugin is Warzone, which we do not do. Make the rules link an option in the config, then amend your PR.

Manager is made for Warzone only lold

**Comment by danielgulic** [comment]
What makes you say that?

**Comment by shadowolfyt** [comment]
> Manager is made for Warzone only lold
Not necessarily, majority of the repos and plugins of the Warzone network are open sourced, like the common example TGM. Other people or servers can take and use this for their own needs.

As per the PR: I agree with @danielgulic "Make the rules link an option in the config, then amend your PR."

**Pull request closed without merging**
